### ISSUE TITLE
Critérios de avaliação:

### ISSUE THREAD

**Issue by gabrielafons** [gabrielafons/projeto-3#7]
Implementação das funcionalidades (2 pontos):

- [ ] cada funcionalidade descrita acima vale 0.4 ponto, se funcionar da forma esperada

- [ ]  será apenas considerado o que está na branch principal do repositório (main ou master) e não serão considerados funcionalidades em outras branches

Uso correto do sistema de versionamento (2 pontos):

- [ ] Uso do GitHub Workflow com issues e branches para cada funcionalidade do projeto (0.5 ponto -  1 ponto se o projeto for individual)

- [ ] Commits com partes que do projeto que funcionam (0.5 ponto - 1 ponto se o projeto for individual)

- [ ] Revisão de PR feita pela outra pessoa para códigos feitos em dupla (0.5 ponto - 0 ponto se o projeto for individual)

- [ ] Projeto feito por todos os integrantes (0.5 ponto - 0 ponto se o projeto for individual)

Desenvolvimento do código (5 pontos - 1 ponto para cada funcionalidade)

- [ ] A correção do código será feita pelo que foi implementado em cada branch. Projetos sem branches receberão zero nesta parte

- [ ] Cada funcionalidade é implementada em uma função

- [ ] As funções não utilizam variáveis globais, a não ser que seja a única forma de resolver o problema

- [ ] As funcionalidades implementadas seguem o que foi pedido

- [ ] Variáveis declaradas com nomes que podem ser entendidos

- [ ] Código que pode ser facilmente estendido

- [ ] Sem loops, desvios condicionais, funções e variáveis desnecessárias

- [ ] Tratamento de erros que podem ocorrer durante a execução do programa

- [ ] Uso de tipos corretos para dados

- [ ] Tratamento correto dos dados inseridos pelo usuário

Documentação no README.md (1 ponto):

- [ ] objetivo do projeto (0.25 ponto)

- [ ] funcionalidades (0.25 ponto)

- [ ] como pode ser compilado e executado (0.5 ponto)

**Comment by IABorges** [comment]
pq os criterios de avaliação virou uma issue??
